// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-leads.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function db(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_leads_default = defineTool({
  name: "list_leads",
  title: "List leads",
  description: "List CRM leads, most recent first. Optionally filter by status.",
  inputSchema: {
    status: z.string().optional().describe("Filter by status (e.g. 'new', 'in_progress', 'client')."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = db(ctx).from("leads").select("id, name, contact, telegram, status, ref_code, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { leads: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-partners.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function db2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_partners_default = defineTool2({
  name: "list_partners",
  title: "List partners",
  description: "List affiliate partners with their referral codes.",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await db2(ctx).from("partners").select("id, name, username, telegram_id, ref_code, traffic_source, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { partners: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-cases.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function db3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_cases_default = defineTool3({
  name: "list_cases",
  title: "List portfolio cases",
  description: "List portfolio/case studies shown in the mini-app.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("Max rows (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await db3(ctx).from("cases").select("*").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { cases: data ?? [] } };
  }
});

// src/lib/mcp/tools/get-stats.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
function db4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_stats_default = defineTool4({
  name: "get_stats",
  title: "CRM stats",
  description: "Return counts of leads, partners, bot users, and clicks.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = db4(ctx);
    const [leads, partners, users, clicks] = await Promise.all([
      client.from("leads").select("id", { count: "exact", head: true }),
      client.from("partners").select("id", { count: "exact", head: true }),
      client.from("bot_users").select("id", { count: "exact", head: true }),
      client.from("clicks").select("id", { count: "exact", head: true })
    ]);
    const stats = {
      leads: leads.count ?? 0,
      partners: partners.count ?? 0,
      bot_users: users.count ?? 0,
      clicks: clicks.count ?? 0
    };
    return { content: [{ type: "text", text: JSON.stringify(stats) }], structuredContent: stats };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function db5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_projects_default = defineTool5({
  name: "list_projects",
  title: "List projects",
  description: "List client projects with status and progress.",
  inputSchema: {
    status: z4.string().optional().describe("Filter by status (e.g. 'active', 'done')."),
    limit: z4.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = db5(ctx).from("projects").select("id, name, client_name, status, progress, mvp_completed_at, github_repo, created_at").order("created_at", { ascending: false }).limit(limit ?? 30);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { projects: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
function db6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tasks_default = defineTool6({
  name: "list_tasks",
  title: "List tasks",
  description: "List project tasks. Filter by project_id and/or status.",
  inputSchema: {
    project_id: z5.string().uuid().optional(),
    status: z5.string().optional().describe("e.g. 'todo', 'in_progress', 'done'."),
    limit: z5.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = db6(ctx).from("tasks").select("id, title, description, status, priority, type, project_id, planned_for_date, completed_at, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (project_id) q = q.eq("project_id", project_id);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { tasks: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-payouts.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z6 } from "npm:zod@^3.25.76";
function db7(ctx) {
  return createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_payouts_default = defineTool7({
  name: "list_payouts",
  title: "List payouts",
  description: "List partner payouts. Filter by status (pending/paid/cancelled).",
  inputSchema: {
    status: z6.enum(["pending", "paid", "cancelled"]).optional(),
    limit: z6.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = db7(ctx).from("payouts").select("id, partner_id, amount, status, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { payouts: data ?? [] } };
  }
});

// src/lib/mcp/tools/update-lead-status.ts
import { createClient as createClient8 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z7 } from "npm:zod@^3.25.76";
function db8(ctx) {
  return createClient8(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var update_lead_status_default = defineTool8({
  name: "update_lead_status",
  title: "Update lead status",
  description: "Change a lead's funnel status (new / in_progress / client / rejected).",
  inputSchema: {
    lead_id: z7.string().uuid().describe("Lead UUID."),
    status: z7.enum(["new", "in_progress", "client", "rejected"]).describe("New status.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ lead_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await db8(ctx).from("leads").update({ status }).eq("id", lead_id).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Lead not found" }], isError: true };
    return { content: [{ type: "text", text: `Updated lead ${data.name ?? lead_id} \u2192 ${status}` }], structuredContent: { lead: data } };
  }
});

// src/lib/mcp/tools/create-task.ts
import { createClient as createClient9 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z8 } from "npm:zod@^3.25.76";
function db9(ctx) {
  return createClient9(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_task_default = defineTool9({
  name: "create_task",
  title: "Create task",
  description: "Add a task to a project. Requires project_id and title.",
  inputSchema: {
    project_id: z8.string().uuid(),
    title: z8.string().min(1).max(500),
    description: z8.string().optional(),
    priority: z8.enum(["low", "medium", "high"]).optional(),
    type: z8.string().optional().describe("Task type, e.g. 'scope' or 'ops'. Default 'ops'."),
    planned_for_date: z8.string().optional().describe("ISO date, e.g. 2026-07-10.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await db9(ctx).from("tasks").insert({
      project_id: input.project_id,
      title: input.title,
      description: input.description ?? null,
      priority: input.priority ?? "medium",
      type: input.type ?? "ops",
      planned_for_date: input.planned_for_date ?? null,
      status: "todo",
      is_manual: true,
      steps: []
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Created task: ${data?.title}` }], structuredContent: { task: data } };
  }
});

// src/lib/mcp/tools/complete-task.ts
import { createClient as createClient10 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z9 } from "npm:zod@^3.25.76";
function db10(ctx) {
  return createClient10(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var complete_task_default = defineTool10({
  name: "complete_task",
  title: "Complete task",
  description: "Mark a task as done.",
  inputSchema: { task_id: z9.string().uuid() },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ task_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await db10(ctx).from("tasks").update({ status: "done" }).eq("id", task_id).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Task not found" }], isError: true };
    return { content: [{ type: "text", text: `Completed: ${data.title}` }], structuredContent: { task: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hkrujkgxitjvgptjolwe";
var mcp_default = defineMcp({
  name: "petr-firstov-crm-mcp",
  title: "Petr Firstov CRM",
  version: "0.1.0",
  instructions: "Read-only access to the Petr Firstov CRM: leads, affiliate partners, portfolio cases, and top-line stats. Use `get_stats` for a quick overview, then drill in with `list_leads`, `list_partners`, or `list_cases`.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_stats_default,
    list_leads_default,
    list_partners_default,
    list_cases_default,
    list_projects_default,
    list_tasks_default,
    list_payouts_default,
    update_lead_status_default,
    create_task_default,
    complete_task_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
